image: registry.gitlab.com/ilyabakhlin/test-image:5.6

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - vendor/

stages:
    - install
    - check
    - test

Composer:
    before_script:
        - composer diagnose
    script:
        - composer install --no-progress
    after_script:
        - composer update
    stage: install

PHP Code Sniffer:
    script:
        - composer sniff
        - composer sniff-tests
    stage: check

PHP Mess Detector:
    script:
        - composer check
        - composer check-tests
    stage: check

PHP 5.6:
    script:
        - composer test
    stage: test
