image: registry.gitlab.com/ilyabakhlin/test-image:5.6

stages:
    - test

PHP 5.6:
    before_script:
        - composer install
    script:
        - ./vendor/bin/phpunit --bootstrap ./vendor/autoload.php --colors=always --configuration ./phpunit.xml
    stage: test
