cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - vendor/

stages:
    - test

.test:
    before_script:
        - composer self-update
        - composer install --no-progress
    script:
        - composer check
        - composer check-tests
        - composer test
    stage: test

PHP 5.6:
    extends: .test
    image: registry.gitlab.com/quorrax/php/libraries/variable-runner:5.6

PHP 7.0:
    extends: .test
    image: registry.gitlab.com/quorrax/php/libraries/variable-runner:7.0

PHP 7.1:
    extends: .test
    image: registry.gitlab.com/quorrax/php/libraries/variable-runner:7.1

PHP 7.2:
    extends: .test
    image: registry.gitlab.com/quorrax/php/libraries/variable-runner:7.2

PHP 7.3:
    extends: .test
    image: registry.gitlab.com/quorrax/php/libraries/variable-runner:7.3

PHP 7.4:
    extends: .test
    image: registry.gitlab.com/quorrax/php/libraries/variable-runner:7.4
