language: php

os: linux

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4

before_install:
    - composer self-update

install:
    - composer install --no-progress
    - composer require --dev --no-progress php-coveralls/php-coveralls
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter

before_script:
    - ./cc-test-reporter before-build

script:
    - composer check
    - composer check-tests
    - composer sniff
    - composer sniff-tests
    - composer test

after_success:
    - ./vendor/bin/phpunit -c ./phpunit.xml --coverage-clover ./clover.xml
    - php ./vendor/bin/php-coveralls -o ./output.json -x ./clover.xml
    - ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT ./clover.xml
