language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4

cache:
    directories:
        - ./vendor

stages:
    - install

jobs:
    include:
        -   name: Composer
            script:
                - comoser install
            stage: install

before_install:
    - curl -s https://getcomposer.org/installer | php -- --install-dir=/home/travis/.phpenv/shims --filename=composer
    - composer diagnose
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter

install:
    - composer install --no-progress

before_script:
    - composer check
    - composer check-test
    - composer sniff
    - composer sniff-test
    - ./cc-test-reporter before-build


script:
    - composer test

after_success:
    - composer require --dev --no-progress php-coveralls/php-coveralls
    - ./vendor/bin/phpunit -c ./phpunit.xml --coverage-clover ./clover.xml
    - ./vendor/bin/php-coveralls -o ./coveralls.json -x ./clover.xml
    - ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT
