language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4

before_install:
    - curl -s https://getcomposer.org/installer | php -- --install-dir=/home/travis/.phpenv/shims --filename=composer
    - composer diagnose

install:
    - composer install --no-progress

before_script:
    - composer check
    - composer check-test
    - composer sniff
    - composer sniff-test

script:
    - composer test

after_success:
    - composer require --dev --no-progress php-coveralls/php-coveralls
    - ./vendor/bin/php-coveralls -v
