language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4

before_install:
    - which composer
    - composer self-update
    - composer diagnose

install:
    - composer install --no-progress

before_script:
    - composer check
    - composer sniff

script:
    - composer test
