language: php

os: linux

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4

before_install:
    - composer self-update

install:
    - composer install --no-progress

before_script:
    - composer check
    - composer check-tests
    - composer sniff
    - composer sniff-tests

script:
    - composer test
